version: '3'

tasks:
  checkpoint:
    dir: scripts
    cmds:
      - npx zx checkpoint.mjs

  download:
    dir: mainrun
    cmds:
      - python3 download_dataset.py

  train:
    deps: [checkpoint, download]
    dir: mainrun
    cmds:
      - sed -i 's/\r$//' train.sh   # fix line endings first
      - chmod +x train.sh           # make it executable
      - ./train.sh 

  submit:
    deps: [checkpoint]
    dir: scripts
    cmds:
      - npx zx submit.mjs
    