model:
  ##############################################
  # CHANGEABLE hyperparameters
  ##############################################
  model_arhitecture: "gpt"
  vocab_size: 16000 
  block_size: 128
  batch_size: 64
  n_layer: 6
  n_head: 8
  d_model: 512
  dropout: 0.1
  bottleneck_size: 256  # Set to 0 for no bottleneck, >0 for bottleneck size