program: train.py
method: random
metric:
  name: val_loss
  goal: minimize

parameters:
  attn_configs.sparse.n_head:
    # values: 4
    values: [4, 8, 16]

  attn_configs.sparse.num_verts:
    # values: 4
    values: [4, 8, 16]

  attn_configs.sparse.sparseblocksize:
    # values: 32
    values: [32, 64, 128]

  attn_configs.sparse.vertsize:
    # values: 64
    values: [64, 128, 256]

  attn_configs.sparse.n_bctx:
    # values: 1
    values: [1, 2, 4]

  attn_configs.sparse.intermediate_dim:
    # values: 0
    values: [0, 64, 128]

