program: train.py   # replace with your script
method: random      # or grid/bayes
metric:
  name: val_loss
  goal: minimize

parameters:
  sparse.attn_type:
    value: "fixed"

  sparse.n_head:
    values: [4, 8, 16]

  sparse.num_verts:
    values: [4, 8, 16]

  sparse.sparseblocksize:
    values: [32, 64, 128]

  sparse.vertsize:
    values: [64, 128, 256]

  sparse.n_bctx:
    values: [1, 2, 4]

  sparse.intermediate_dim:
    values: [0, 64, 128]   # 0 = normal, >0 = bottleneck
