program: train.py
method: grid   # or grid, or bayes
metric:
  name: val/loss
  goal: minimize
parameters:
  lr:
    values: [  0.015 , 0.012 , 0.01, 0.007 ,  0.005]
  batch_size:
    values: [64 , 128]
  context_length:
    values:  [256]
  optimizer:
    values: ["adamw"]
  dropout:
    values: [0.1, 0.2, 0.3 , 0.4]
  weight_decay:
    values: [0.0, 0.05,  0.1 , 0.12 , 0.15]
  d_model:
    values: [ 128, 256]
  n_layer:
    values: [ 6,  8 ]

  init_method:
    values: ['xavier' , 'normal' , 'kaiming', 'uniform']


