program: train.py
method: grid   # or grid, or bayes
metric:
  name: val/loss
  goal: minimize
parameters:
  lr:
    values: [ 0.012 , 0.01, 0.007 ,  0.005]
  batch_size:
    values: [128, 256 ]
  context_length:
    values: [256 , 512]
  optimizer:
    values: ["sgd", "adamw", "adam", "adagrad"]
  dropout:
    values: [0.1, 0.2, 0.3 , 0.4]
  weight_decay:
    values: [0.0, 0.01, 0.1]
  d_model:
    values: [ 128, 256, 512 ]
  n_layer:
    values: [ 4, 6, 8, 10]
