name: Run Sweep

on:
  workflow_dispatch:   # Trigger manually

jobs:
  sweep:
    runs-on: [self-hosted, x64, linux, docker]

    steps:
      - name: Update repo
        run: |
          cd /home/labadmin/Documents/mainrun
          git reset --hard
          git pull origin main

      - name: Run Sweep Agent in Docker
        env:
          SWEEP_ID: ${{ secrets.SWEEP_API }}
        run: |
          docker run --rm --gpus all \
          -v /home/labadmin/Documents/mainrun:/workspace \
          -w /workspace/mainrun \
          --env-file /home/labadmin/Documents/mainrun/.env \
          -e WANDB_PYTHON_EXECUTABLE=/usr/bin/python3 \
          -e PYTHONPATH=/workspace/mainrun \
          mainrun-env \
          bash -c "ln -s /usr/bin/python3 /usr/bin/python && \
                  git config --global --add safe.directory /workspace && \
                  git config --global user.email 'teedsingyau@gmail.com' && \
                  git config --global user.name 'Ted Lo' && \
                  wandb agent arc_agi/gpt-from-scratch/${SWEEP_ID}"


      - name: Cleanup WandB logs
        run: |
          if [ -d "/home/labadmin/Documents/mainrun/mainrun/wandb" ]; then
            sudo rm -rf /home/labadmin/Documents/mainrun/mainrun/wandb
            echo "Deleted wandb logs"
          else
            echo "No wandb folder found"
          fi

      - name: Cleanup __pycache__
        run: |
          if [ -d "/home/labadmin/Documents/mainrun/mainrun/__pycache__" ]; then
            sudo rm -rf /home/labadmin/Documents/mainrun/mainrun/__pycache__
            echo "Deleted __pycache__"
          else
            echo "No __pycache__ folder found"
          fi
