name: Run Sweep

on:
  workflow_dispatch:   # Trigger manually

jobs:
  sweep:
    runs-on: [self-hosted, x64, linux, docker]

    steps:
      - name: Update repo
        run: |
          cd /home/labadmin/Documents/mainrun
          git reset --hard
          git pull origin main

      - name: Run Sweep Agent in Docker
        env:
          SWEEP_ID: ${{ secrets.SWEEP_API }}
        run: |
          docker run --rm --gpus all \
          -v /home/labadmin/Documents/mainrun:/workspace \
          -w /workspace/mainrun \
          --env-file /home/labadmin/Documents/mainrun/.env \
          -e WANDB_PYTHON_EXECUTABLE=/usr/bin/python3 \
          -e PYTHONPATH=/workspace/mainrun \
          -e SWEEP_ID=${SWEEP_ID} \
          -e PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
          mainrun-env \
          bash -c "ln -s /usr/bin/python3 /usr/bin/python && \
                  git config --global --add safe.directory /workspace && \
                  git config --global user.email 'teedsingyau@gmail.com' && \
                  git config --global user.name 'Ted Lo' && \
                  task train"


    