name: Train Model

on:
  workflow_dispatch:   # This makes it manual

jobs:
  train:
    runs-on: [self-hosted, x64, linux ,docker]  # your self-hosted runner
    steps:
      - uses: actions/checkout@v3

      - name: Load .env
        run: |
            export $(grep -v '^#' .env | xargs)

      - name: Update local repo
        run: |
            cd /home/labadmin/Documents/mainrun
            git reset --hard origin/main
            git pull origin main

      - name: Run training in Docker
        run: |
            docker run --rm --gpus all \
                -v $GITHUB_WORKSPACE:/workspace \
                -w /workspace \
                -e WANDB_API_KEY=$WANDB_API_KEY \
                mainrun-env \
                /bin/bash -c "\
                    git config --global --add safe.directory /workspace && \
                    git config --global user.email 'teedsingyau@gmail.com' && \
                    git config --global user.name 'Ted Lo' && \
                    task train \
                    rm -rf /workspace/wandb"
            