name: Train Model

on:
  workflow_dispatch:   # This makes it manual

jobs:
  train:
    runs-on: [self-hosted, x64, linux ,docker]  # your self-hosted runner
    steps:
      - uses: actions/checkout@v3

      - name: Load .env
        run: |
            export $(grep -v '^#' .env | xargs)

      - name: Run training in Docker
        env:
            WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
            docker run --rm --gpus all \
                -v $GITHUB_WORKSPACE:/workspace \
                -w /workspace \
                -e WANDB_API_KEY=$WANDB_API_KEY \
                mainrun-env \
                /bin/bash -c "\
                    git config --global --add safe.directory /workspace && \
                    git config --global user.email 'teedsingyau@gmail.com' && \
                    git config --global user.name 'Ted Lo' && \
                    task train"
  
      - name: Remove WandB logs
        run: |
            if [ -d "./wandb" ]; then
            sudo rm -rf ./wandb
            echo "Deleted wandb logs"
            else
            echo "No wandb folder found"
            fi