name: Train Model

on:
  workflow_dispatch:   # Run manually

jobs:
  train:
    runs-on: [self-hosted, x64, linux, docker]

    steps:
      - name: Update repo
        run: |
          cd /home/labadmin/Documents/mainrun
          git reset --hard
          git pull origin main

      - name: Run training in Docker
        run: |
          docker run --rm --gpus all \
            -v /home/labadmin/Documents/mainrun:/workspace \
            -w /workspace \
            --env-file /home/labadmin/Documents/mainrun/.env \
            mainrun-env-new \
              bash -c " git config --global --add safe.directory /workspace && \
                       git config --global user.email 'teedsingyau@gmail.com' && \
                       git config --global user.name 'Ted Lo' && \
                       task train"

    