name: Train Model

on:
  workflow_dispatch:
    inputs:
      use_gpu:
        description: 'Use GPU?'
        required: true
        default: 'true'

jobs:
  train:
    runs-on: [self-hosted, x64, linux, docker]

    steps:
      - name: Update repo
        run: |
          cd /home/labadmin/Documents/mainrun
          git reset --hard
          git pull origin main

      - name: Run training in Docker
        run: |
          cd /home/labadmin/Documents/mainrun
          USE_GPU=true   # change to false if you don't want GPU
          GPU_FLAG=""
          if [ "$USE_GPU" = "true" ]; then
            GPU_FLAG="--gpus all"
          fi

          docker run --rm $GPU_FLAG \
            -v /home/labadmin/Documents/mainrun:/workspace \
            -w /workspace \
            --env-file /home/labadmin/Documents/mainrun/.env \
            mainrun-env-new \
            bash -c "git config --global --add safe.directory /workspace && \
                    git config --global user.email 'teedsingyau@gmail.com' && \
                    git config --global user.name 'Ted Lo' && \
                    task train"


    