program: train.py
method: grid   # or grid, or bayes
metric:
  name: val/loss
  goal: minimize
parameters:
  sparsek.n_head:
    values: [ 8, 10]
  sparsek.epilson:
    values: [1e-6 , 5e-6 , 7e-6]
  sparsek.k:
    values: [32 , 64 ]
