program: train.py
method: grid   # or grid, or bayes
metric:
  name: val/loss
  goal: minimize
parameters:
  attn_configs.sparsek.n_head:
    values: [ 8, 16]
  attn_configs.sparsek.epilson:
    values: [1e-6 , 5e-6 , 7e-6]
  attn_configs.sparsek.k:
    values: [32 , 64 ]
  model_configs.gpt.d_model:
    values: [128, 256]